name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl
      OJDBC_DIR: ${{ github.workspace }}/ojdbc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
      shell: bash
      
    - name: Instalar Liquibase y extensión de Oracle
      run: |
        mkdir -p $HOME/liquibase
        curl -sSL https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.tar.gz \
          | tar xz -C $HOME/liquibase --strip-components=1
        curl -sSL https://github.com/liquibase/liquibase-oracle/releases/download/v1.0.0/liquibase-oracle-1.0.0.jar \
          -o $HOME/liquibase/lib/liquibase-oracle.jar
        echo "$HOME/liquibase" >> $GITHUB_PATH
      shell: bash
  
    - name: Configurar variables de entorno
      run: |
        echo "CLASSPATH=$HOME/liquibase/lib/liquibase-oracle.jar:${OJDBC_DIR}/ojdbc8.jar:${OJDBC_DIR}/oraclepki.jar:${OJDBC_DIR}/osdt_core.jar:${OJDBC_DIR}/osdt_cert.jar" >> $GITHUB_ENV
        echo "TNS_ADMIN=${GITHUB_WORKSPACE}/Wallet_APEXDEVDB" >> $GITHUB_ENV
      shell: bash

    - name: Ejecutar Liquibase update
      run: |
        liquibase \
          --driver=oracle.jdbc.OracleDriver \
          --url="jdbc:oracle:thin:@${DB_ALIAS}" \
          --username=${DB_USER} \
          --password=${DB_PASSWORD} \
          --changeLogFile=changelog_001.sql \
          update
