name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl
      OJDBC_DIR: ${{ github.workspace }}/ojdbc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
      shell: bash
      
    - name: Instalar Liquibase y extensión de Oracle
      run: |
       curl -sSL -o liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.zip
       unzip -q liquibase.zip -d liquibase
       curl -sSL -o liquibase/lib/liquibase-oracle-1.0.0.jar https://github.com/liquibase/liquibase-oracle/releases/download/v1.0.0/liquibase-oracle-1.0.0.jar  
      shell: bash  
      
    - name: Copiar librerías de seguridad al lib de Liquibase
      run: |
        cp ${TNS_ADMIN}/../*.jar liquibase/lib/ || true
        cp ${GITHUB_WORKSPACE}/*.jar liquibase/lib/ || true
      shell: bash

    - name: Configurar entorno Liquibase
      run: |
        echo "LIQUIBASE_HOME=${GITHUB_WORKSPACE}/liquibase" >> $GITHUB_ENV
        echo "PATH=${GITHUB_WORKSPACE}/liquibase:\$PATH" >> $GITHUB_ENV
        echo "TNS_ADMIN=${GITHUB_WORKSPACE}/Wallet_APEXDEVDB" >> $GITHUB_ENV
      shell: bash

    - name: Ejecutar Liquibase update
      run: bash ./run_liquibase.sh
       env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ALIAS: apexdevdb_high
