name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl
      OJDBC_DIR: ${{ github.workspace }}/ojdbc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
      shell: bash
      
    - name: Instalar Liquibase y extensión de Oracle
      run: |
       curl -sSL https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.tar.gz | tar xz
       curl -sSL https://github.com/liquibase/liquibase-oracle/releases/download/v1.0.0/liquibase-oracle-1.0.0.jar -o liquibase-oracle.jar
      shell: bash
  
    - name: Configurar variables de entorno
      run: |
       echo "export LIQUIBASE_HOME=${GITHUB_WORKSPACE}/liquibase" >> $GITHUB_ENV
       echo "export CLASSPATH=${GITHUB_WORKSPACE}/liquibase-oracle.jar:${GITHUB_WORKSPACE}/ojdbc8.jar:${GITHUB_WORKSPACE}/oraclepki.jar:${GITHUB_WORKSPACE}/osdt_core.jar:${GITHUB_WORKSPACE}/osdt_cert.jar" >> $GITHUB_ENV
       echo "export TNS_ADMIN=${GITHUB_WORKSPACE}/Wallet_APEXDEVDB" >> $GITHUB_ENV
      shell: bash

    - name: Ejecutar Liquibase update
      run: |
       liquibase --driver=oracle.jdbc.OracleDriver \
              --url="jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-phoenix-1.oraclecloud.com))(connect_data=(service_name=g715fad23c28830_apexdevdb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))" \
              --username=${DB_USER} \
              --password=${DB_PASSWORD} \
              --changeLogFile=changelog_001.sql \
              update
       env:
        DB_USER: GTIM
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  
   
