name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      LIQUIBASE_HOME: ${{ github.workspace }}/liquibase
      OJDBC_DIR: ${{ github.workspace }}/ojdbc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget curl

    - name: Install SQLcl
      run: |
        wget --no-cookies --no-check-certificate \
          --header "Cookie: oraclelicense=accept-securebackup-cookie" \
          https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"

    - name: Install Liquibase and Oracle extension
      run: |
        mkdir -p ${LIQUIBASE_HOME}
        curl -sSL https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.tar.gz | tar -xz -C ${LIQUIBASE_HOME} --strip-components=1
        curl -sSL https://github.com/liquibase/liquibase-oracle/releases/download/v1.0.0/liquibase-or
