name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl
      OJDBC_DIR: ${{ github.workspace }}/ojdbc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Install Liquibase + Oracle extension
      run: |
       mkdir -p $HOME/liquibase
       curl -sSL https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.zip -o liquibase.zip
       unzip -q liquibase.zip -d $HOME/liquibase

       # Descargar extensión de Oracle
       curl -sSL https://github.com/liquibase/liquibase-oracle/releases/download/v1.0.0/liquibase-oracle-1.0.0.jar \
       -o $HOME/liquibase/lib/liquibase-oracle.jar

       # Dar permisos al binario
       chmod +x $HOME/liquibase/liquibase

       # Exportar path
       echo "$HOME/liquibase" >> $GITHUB_PATH
      shell: bash
    
    - name: Download JDBC and PKI jars
      run: |
        mkdir -p ${OJDBC_DIR}
        curl -sSL https://download.oracle.com/otn-pub/otn_software/jdbc/ojdbc8-full/21/ojdbc8.jar -o ${OJDBC_DIR}/ojdbc8.jar
        curl -sSL https://download.oracle.com/otn-pub/otn_software/jdbc/ojdbc8-full/21/oraclepki.jar -o ${OJDBC_DIR}/oraclepki.jar
        curl -sSL https://download.oracle.com/otn-pub/otn_software/jdbc/ojdbc8-full/21/osdt_core.jar -o ${OJDBC_DIR}/osdt_core.jar
        curl -sSL https://download.oracle.com/otn-pub/otn_software/jdbc/ojdbc8-full/21/osdt_cert.jar -o ${OJDBC_DIR}/osdt_cert.jar
      shell: bash

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
        echo "TNS_ADMIN=${TNS_ADMIN}" >> $GITHUB_ENV
      shell: bash

    - name: Run SQL script on Oracle ADB
      run: |
        export PATH="${SQLCL_DIR}/sqlcl/bin:$PATH"
        export TNS_ADMIN="${GITHUB_WORKSPACE}/Wallet_APEXDEVDB"
        export PATH="${GITHUB_WORKSPACE}/sqlcl/sqlcl/bin:$PATH"
        
        sql -s "\"${DB_USER}\"/${DB_PASSWORD}@${DB_ALIAS}" SELECT * FROM EEEMPLOYEES;
        liquibase \
         --url="jdbc:oracle:thin:@//adb.us-phoenix-1.oraclecloud.com:1522/g715fad23c28830_apexdevdb_high" \
         --username=GTIM \
         --password=${DB_PASSWORD} \
         --changeLogFile=changelog_001.sql \
         --logLevel=debug
         update
      env:
        TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
        DB_ALIAS: apexdevdb_high
        DB_USER: GTIM
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SQLCL_DIR: ${{ github.workspace }}/sqlcl
