name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
        echo "TNS_ADMIN=${TNS_ADMIN}" >> $GITHUB_ENV
      shell: bash

    - name: Run SQL script on Oracle ADB
      run: |
        export PATH="${SQLCL_DIR}/sqlcl/bin:$PATH"
        export TNS_ADMIN="${GITHUB_WORKSPACE}/Wallet_APEXDEVDB"
        export PATH="${GITHUB_WORKSPACE}/sqlcl/sqlcl/bin:$PATH"
        
        sql -s "\"${DB_USER}\"/${DB_PASSWORD}@${DB_ALIAS}" @BDD/TABLES/EMPLOYEES.sql
        liquibase \
         --url="jdbc:oracle:thin:@//adb.us-phoenix-1.oraclecloud.com:1522/g715fad23c28830_apexdevdb_high" \
         --username=GTIM \
         --password=${DB_PASSWORD} \
         --changeLogFile=changelog_001.sql \
         --logLevel=debug
         update
      env:
        TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
        DB_ALIAS: apexdevdb_high
        DB_USER: GTIM
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SQLCL_DIR: ${{ github.workspace }}/sqlcl
