name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
      DB_ALIAS: apexdevdb_high
      DB_USER: GTIM
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  
      
    - name: Install LB
      run: |
        curl -LO https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.zip
        unzip liquibase-*.zip -d $HOME/liquibase
        echo "$HOME/liquibase" >> $GITHUB_PATH      

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o Wallet_APEXDEVDB.zip -d "${TNS_ADMIN}"
      shell: bash

    - name: Add Oracle JDBC wallet libraries
      run: |
        mkdir -p $HOME/ojdbc
        curl -LO https://download.oracle.com/otn-pub/otn_software/java/ojdbc8-full/ojdbc8-full.tar.gz
        tar -xzf ojdbc8-full.tar.gz -C $HOME/ojdbc
        cp $HOME/ojdbc/*.jar $HOME/liquibase/lib/
        
    - name: Run SQL script on Oracle ADB
      run: |
        liquibase --driver=oracle.jdbc.OracleDriver \
                  --url="jdbc:oracle:thin:@${DB_ALIAS}?TNS_ADMIN=${TNS_ADMIN}" \
                  --username=${DB_USER} \
                  --password=${DB_PASSWORD} \
                  --changeLogFile=changelog_001.sql \
                  update
      env:
        TNS_ADMIN: ${{ github.workspace }}/Wallet_APEXDEVDB
        DB_ALIAS: apexdevdb_high
        DB_USER: GTIM
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SQLCL_DIR: ${{ github.workspace }}/sqlcl
